---
resources:
- name: concourse-arm64
  type: git
  icon: github
  source:
    uri: https://github.com/robinhuiser/concourse-arm64

jobs:
- name: test-job
  public: true
  plan:
  - get: concourse-arm64
    trigger: true
  - task: build-task
    config:
      platform: linux
      type: registry-image
      source:
        repository: rdclda/concourse-oci-build-task
        tag: latest
      inputs:
      - name: context
        path: concourse-arm64/external-tasks/oci-build/example
      outputs:
      - name: image
      caches:
      - path: cache
      run: {path: build}